export const QUERY_KEYS = {
  USER: 'user',
  COMPANY: 'company',
  PROJECTS: 'projects',
  PROJECT: 'project',
  EMPLOYEES: 'employees',
  EMPLOYEE: 'employee',
  TASKS: 'tasks',
  TASK: 'task',
  PROFILE: 'profile',
  EVENTS: 'events',
  CALENDAR: 'calendar',
  SEARCH: 'search',
  ATTACHMENTS: 'attachments',
};
