export const QUERY_KEYS = {
  USER: 'user',
  COMPANY: 'company',
  PROJECTS: 'projects',
  FOLDERLESS_PROJECTS: 'folderlessProjects',
  PROJECT: 'project',
  EMPLOYEES: 'employees',
  EMPLOYEE: 'employee',
  TASKS: 'tasks',
  TASK: 'task',
  PROFILE: 'profile',
  EVENTS: 'events',
  CALENDAR: 'calendar',
  SEARCH: 'search',
  ATTACHMENTS: 'attachments',
  COMMENTS: 'comments',
  TIMELOG: 'timelog',
  NOTIFICATIONS: 'notifications',
  FOLDERS: 'folders',
};
